name: ER3D
description: Euler Rotations in 3-Dimensions
full_description: 'Three-dimensional (3D) rotational kinematics are one of the most important, and yet also one of the most easily misunderstood topics of advanced mechanical engineering dynamics and trajectory simulation modeling. The ER3D mobile app aims to be a teaching aid for students and interested learners who want to understand these fundamental kinematics in an interactive and visually appealing setting, including in Augmented Reality.
<br>Features of the app include:
<br>- Sliders to update yaw, pitch, and roll angles in a 3-2-1 sequence
<br>- Context menus with text description of the kinematic properties
<br>- Globe Earth that may be rotated to visualize locations at different latitudes and longitudes
<br>- Gyroscope model for teaching 3-1-3 rotation sequence'
iOS: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - yawRK.gif
  - pitchRK.gif
  - rollRK.gif
  - yawPitchRollRK.gif
